src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Il existe deja un compte avec ce mail')]

class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column]
    private ?bool $Active = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->Active;
    }

    public function setActive(bool $Active): static
    {
        $this->Active = $Active;

        return $this;
    }
   

}

templates/parts/footer.html.twig
<footer class="footer" style="background-color: black; color: white; margin-top: 50px; padding:20px;">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h5>Contactez-nous</h5>
                <ul class="list-unstyled">
                    <li>Email: dissi@essci.fr</li>
                    <li>Téléphone: 0234567890</li>
                    <li>Adresse: Campus de l'Espace, Vernon, France</li>
                </ul>
            </div>
            <div class="col-md-6">
                <h5>Liens rapides</h5>
                <ul class="list-unstyled">
                    <li><a href="{{path('app_home')}} ">Accueil</a></li>
                    <li><a href="{{ path('app_articles_index') }}" >Liste d'articles</a></li>
                    <li><a href="{{path('app_articles_new')}} ">Créer un article</a></li>
                </ul>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-12">
                <p class="text-center">© {{ "now"|date("Y") }} Quentin & Mohamed. Tous droits réservés.</p>
            </div>
        </div>
    </div>
</footer>

templates/parts/nav.html.twig
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: black; color: white; padding: 10px; ">
            <div class="container-fluid">
            <a class="navbar-brand" href="{{ path('app_home')}}">Accueil</a>
            <a href="{{ path('app_articles_index') }}" class="navbar-brand">Articles</a>
            {# {{ dump(app.user) }} #}
            <ul class="navbar-nav ms-auto nb-2 nb-lg-0">
            
            {# Une fois que l'User veut supprimer son compte, il se deconnectera directement et son compte sera desactivé #}
            {% if (app.user) and app.user.active == true %}
            {# Si le User est connecté, il pourra voir Se deconnecter/MonCompte #}
                <li class="nav-item"><a class="nav-link" href="{{ path('app_logout')}}">Se deconnecter</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ path('app_profil_show')}}">Mon compte</a></li>
            {% else %}
            {# Quand le User est deconnecté il voit SeConnecter et S'enregistrer #}
                <li class="nav-item"><a class="nav-link" href="{{ path('app_login')}}">Se connecter</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ path('app_register')}}">S'enregistrer</a></li>
            {% endif %}

               
            </ul>
            </div>
        </div>
</nav>